#include <iostream>
#include <algorithm>
#include <vector>
#include <unordered_map>
#include <string>
using std::string;
using std::unordered_map;
using std::cin;
using std::cout;
using std::endl;
using std::max;
using std::min;
using std::vector;